/*
   Copyright 2005 Ilya Konstantinov

   This file is part of mozTrayBiff.

   mozTrayBiff is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   mozTrayBiff is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with mozTrayBiff; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/*
	This file describes an XPCOM interface accessible from
	scripting and intended for communications between the
	JS-based chrome and the native component.
*/

#include "nsISupports.idl"

[scriptable, uuid(8bb6e1ca-3b18-45dd-a397-2a20cc6c43ae)]
interface nsIMessengerFreeDesktopIntegration : nsISupports
{
  const unsigned short MAIL_HW_INDICATOR_OK = 0;
  const unsigned short MAIL_HW_INDICATOR_MISSING = 1;
  const unsigned short MAIL_HW_INDICATOR_INACCESSIBLE = 2;

  readonly attribute short mailHwIndicatorStatus;
};
