#!/bin/bash

# Try to guess the Mozilla platform string.
# For now, we're unable to determine it from Mozilla itself.

if test -z "$CC"; then
    CC=cc
fi
PLATFORM=`uname -s`_
MACHINE=`uname -p 2>/dev/null`
if [ $? != 0 -o $MACHINE = "unknown" ]; then
	MACHINE=`uname -m`
fi
case $MACHINE in
*86)
	PLATFORM=${PLATFORM}x86
	;;
powerpc*)
	PLATFORM=${PLATFORM}ppc
	;;
Alpha | alpha | ALPHA)
	PLATFORM=${PLATFORM}Alpha
	;;
x86_64 | sparc | ppc | ia64)
	PLATFORM=${PLATFORM}${MACHINE}
	;;
esac

if ${CC} --version 2>/dev/null | grep GCC > /dev/null; then
	PLATFORM=${PLATFORM}-gcc3
else
    if ${CC} -V 2>&1 | grep 'Sun C' >/dev/null; then
	    PLATFORM=${PLATFORM}-sunc
    fi
fi

echo $PLATFORM
